# fly.toml app configuration file generated for snipeit on 2024-12-31T18:50:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snipeit'
primary_region = 'lhr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]
  image = "snipe/snipe-it:latest"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
